title: ちょっぷすてぃっくすますたー
description: 新感覚派FPS??2020年夏リリース予定！(kamo)
logo: https://raw.githubusercontent.com/Tsurumiya/ChopsticksMaster/master/assets/images/logo.png
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
